title: Awesome Course Collection
description: Collecting several available awesome online courses, related to Mathematics, Computer Science, Finance, and Humanities.
theme: just-the-docs

url: https://chihhsichen.github.io/awesome-course-collection

nav_sort: Alexander

toc_enabled: true

aux_links:
  Chih-Hsi Chen: https://chihhsichen.github.io
