title: Awesome Course Collection
description: Collecting several available awesome online courses, related to Mathematics, Computer Science, Finance, and Humanities.
theme: just-the-docs

url: https://chihhsichen.github.io/awesome-course-collection

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
